### ISSUE TITLE
单独挂载config.yaml后报错

### ISSUE THREAD

**Issue by SuZixiong** [Sagit-chu/mosdns-container#9]
报错为无法加载
`2022-05-17T03:16:55.757Z	fatal	coremain/run.go:37	failed to load config	{"error": "failed to init plugin query_cn: failed to load entry ext:./geosite.dat:cn: open ./geosite.dat: no such file or directory"}`
 
```
version: '3.3'
services:
    mosdns:
        container_name: mosdns
        ports:
            - '5454:53/udp'
            - '5454:53/tcp'
        image: '601096721/mosdns:latest'
        volumes:
           - /home/mosdns_data/config.yaml:/etc/mosdns/config.yaml
```
